services:
  gai-ttt-svr-llamacpp:
    image: kakkoii1337/gai-ttt-svr-llamacpp:1.0.10
    environment:
      DEFAULT_GENERATOR: "ttt-llamacpp-dolphin"
      SWAGGER_URL: "/doc"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ~/.gai:/root/.gai
    ports:
      - "12031:12031"
      - "5678:5678"
    networks:
      - default
    restart: always
    command: >
      python -m debugpy --listen 0.0.0.0:5678 main.py
    #command: python -m debugpy --listen 0.0.0.0:5678 main.py --wait-for-client
    #command: sleep infinity

