[build-system]
requires = [ "poetry-core>=1.8.3",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "gai-ttt-svr"
version = "0.204"
description = "Refer to https://gai-labs.github.io/gai for more information"
authors = [ "kakkoii1337 <kakkoii1337@gmail.com>",]
license = "MIT"
classifiers = [ "Programming Language :: Python :: 3.10", "Development Status :: 3 - Alpha", "License :: OSI Approved :: MIT License", "Intended Audience :: Science/Research", "Intended Audience :: Developers", "Operating System :: OS Independent", "Topic :: Software Development", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: Scientific/Engineering :: Artificial Intelligence",]
include = []
[[tool.poetry.packages]]
include = "gai/ttt/server"
from = "./src"

[tool.poetry.dependencies]
python = "^3.10, <3.12"
accelerate = "0.30.1"
bitsandbytes = "0.43.3"
colorlog = "6.8.2"
debugpy = "1.8.5"
fastapi = "^0.112.0"
httpx = "^0.27.0"
jsonschema = "4.22.0"
lm-format-enforcer = "^0.10.6"
markdownify = "^0.13.1"
numpy = "^1.26.4, <2.0.0"
openai = "^1.40.0, <2.0.0"
pillow = "^10.4, <11.0"
python-dotenv = "^1.0.1"
pydantic = "^2.8.2"
pynvml = "11.5.3"
rich = "^13.7.1"
termcolor = "*"
torch = "2.2.0"
torchaudio = "2.2.0"
tokenizers = ">=0.19,<0.20"
torchvision = "0.17.0"
transformers = "^4.44.0"
uvicorn = "^0.23.2"
gai-sdk = "^0.251"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
nox = "^2024.4.15"
twine = "^5.1.1"
"keyrings.alt" = "^5.0.1"
ipykernel = "^6.29.5"
toml = "^0.10.2"
flake8 = "^7.1.1"
pytest-ordering = "^0.6"
