version: 1.1
gai_url: "http://localhost:12033"
logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    filename: ""
    filemode: "a"
    stream: "stdout"
    loggers:
        gai.ttt: "DEBUG"
        gai.common.http_utils: "DEBUG"
generators:
    ttt:
        default: "ttt-exllamav2-dolphin"
        configs:
            ttt-exllamav2-dolphin:
                type: "ttt"
                engine: "exllamav2"
                model: "dolphin"
                name: "ttt-exllamav2-dolphin"
                model_path: "models/exllamav2-dolphin"
                max_seq_len: 8192
                prompt_format: "mistral"
                hyperparameters:
                    temperature: 0.85
                    top_p: 0.8
                    top_k: 50
                    max_tokens: 1000
                    tool_choice: "auto"
                    max_retries: 5
                    stop: ["<|im_end|>", "</s>", "[/INST]"]
                extra:                    
                    no_flash_attn: true
                    seed: null
                    decode_special_tokens: false
                module:
                    name: "gai.ttt.server.gai_exllamav2"
                    class: "GaiExLlamav2"
            ttt-exllamav2-mistral7b:
                type: "ttt"
                engine: "exllamav2"
                model: "mistral7b"
                name: "ttt-exllamav2-mistral7b"
                model_path: "models/exllamav2-mistral7b"
                model_basename: "model"
                max_seq_len: 8192
                prompt_format: "mistral"
                hyperparameters:
                    temperature: 0.85
                    top_p: 0.8
                    top_k: 50
                    max_tokens: 1000
                    tool_choice: "auto"
                    max_retries: 5
                    stop: ["<|im_end|>", "</s>", "[/INST]"]
                extra:
                    no_flash_attn: true
                    seed: null
                    decode_special_tokens: false
                module:
                    name: "gai.ttt.server.gai_exllamav2"
                    class: "GaiExLlamav2"
